### ISSUE TITLE
Broken flags via gulp

### ISSUE THREAD

**Issue by Downchuck** [tkellen/js-v8flags#16] opened 2015-04-04 17:31 UTC
This started showing up in my builds, apparently following 2.0.3.

```
+ gulp test
undefined:1
_code_verbose","--print_builtin_code","--sodium","--print_all_code"]["--use_st
                                                                    ^
SyntaxError: Unexpected token [
    at Object.parse (native)
    at /web/sites/build.jumis.com/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/gulp/node_modules/v8flags/index.js:70:28
    at FSReqWrap.oncomplete (fs.js:99:15)
```

Resetting the cache file seems to have fixed the issue:
```sh
cd /path/to/jenkins/home/dir;
mv .v8flags.3.28.73.jenkins.json .v8flags.3.28.73.jenkins.json-broken
```

**Comment by tkellen** [comment] 2015-04-04 19:46
Have you been able to reproduce the problem? If yes, would you mind sharing how?

**Comment by Downchuck** [comment] 2015-04-04 20:00
No repro: seems like an update in versions lead to the cache file being
appended to.

A try/catch statement on that section of code could at least catch the
error, and since it's just a cache check, and the error is just in the JSON
parse call: the program could handle the error transparently, and keep
running.

**Comment by phated** [comment] 2015-04-04 22:39
It's interesting that the `temp` directory on jenkins is also the home directory.  Also, doesn't jenkins not clean up after a build?  This seems really strange for a build server.

**Comment by Downchuck** [comment] 2015-04-04 23:01
It's the nodejs Jenkins plugin, configured to re-use node modules (as
opposed to re-downloading/installing).

**Comment by tkellen** [comment] 2015-04-04 23:04
I'm mystified as to how it could be appending to the file, though.
https://github.com/tkellen/js-v8flags/blob/master/index.js#L85 should prevent that.

**Comment by phated** [comment] 2015-04-05 01:10
@tkellen could there be an issue with async reading/writing from 2 instances/processes?  I know that npm likes to spawn child processes.

**Comment by Downchuck** [comment] 2015-04-05 01:38
Looks like a possibility to me as well. In my case there were two processes
running, concurrently. May be that flush is not called. It doesn't look
like an atomic write to temp file then rename -- operation.

**Comment by Mellbourn** [comment] 2015-04-16 11:01
We had this problem too.
It occurred because very many TeamCity builds were triggered almost simultaneously. This seems to have caused a double write of the cache file.
The cache file was saved in the user home directory. Naturally, that folder is never cleaned out by TeamCity. So once the corrupted cache file was written, all our builds kept failing, no matter how much they cleaned up their working directory.

We had to write a TeamCity build step that cleaned up corrupted cache files (we are on Windows, so this is in PowerShell):

```PowerShell
$v8flagspattern = (Join-Path $env:USERPROFILE (".v8flags.*." + $env:USERNAME + ".json"))
Get-ChildItem $v8flagspattern | ForEach-Object {
    $v8flagsfile = $_.FullName
    try {
      Get-Content $v8flagsfile | ConvertFrom-Json | Out-Null
    }
    catch {
      $warningMessage = ("Cleaning up corrupted v8flags cachefile: `"" + $v8flagsfile + "`"")
      Write-Warning $warningMessage
      Remove-Item $v8flagsfile
      throw $warningMessage
    }
}
```

**Comment by jacekkolasa** [comment] 2015-04-16 13:32
@Mellbourn Works perfectly, thanks!

**Comment by tkellen** [comment] 2015-04-16 23:56
Just pushed a fix for v8flags.  Can ya'll confirm this is resolved and close if it is?

**Comment by Owemeone** [comment] 2015-04-17 12:53
@tkellen I ran into this issue and for me the fix is working

**Closed** 2015-04-17 12:53 UTC
