### ISSUE TITLE
getFlags fails in Electron environment

### ISSUE THREAD

**Issue by s-a** [tkellen/js-v8flags#25] opened 2015-07-27 11:08 UTC
![image](https://cloud.githubusercontent.com/assets/1270662/8904509/31c7a13a-3460-11e5-89a2-ea2e1622c617.png)

I am facing this running Gulp tasks in Electron environments. Any ideas how I can workaround this issue?

ref: https://github.com/s-a/iron-node/issues/22

**Comment by tkellen** [comment] 2015-07-27 17:40
Can you provide a repo that I can reproduce this with? I'd be happy to make a fix.

**Comment by phated** [comment] 2015-07-27 17:55
@tkellen I think it would just need to exit early because electron shouldn't be restarted (bootup is fairly slow)

**Comment by tkellen** [comment] 2015-07-27 17:58
Agreed. I just need a safe heuristic to determine if the environment is electron. I haven't had time to spin it up to examine the process object. Do you have that handy?

**Comment by s-a** [comment] 2015-07-27 17:58
I currently prepare an example to reproduce. Just a minute ... Stay tuned. My app is not a commandline app. It is a GUI App so it will not exit until user close it.

**Comment by s-a** [comment] 2015-07-27 18:06
```bash
git clone https://github.com/s-a/iron-node.git
cd iron-node
npm install

git clone https://github.com/s-a/gulp-iron-node-test.git
cd gulp-iron-node-test
npm install gulp
node node_modules/gulp/bin/gulp.js # should log "hello world to console"
# to start gulp in electron environment start
cd .../iron-node
npm run dev .../gulp-iron-node-test/node_modules/gulp\bin\gulp.js
# this will not execute gulp task correctly but will reproduce the error.

# finally it should work as following
npm install iron-node -g
cd gulp-iron-node-test
iron-node node_modules/gulp/bin/gulp.js
```

**Comment by s-a** [comment] 2015-07-27 18:09
Can you work with this?

**Comment by tkellen** [comment] 2015-07-27 18:09
Trying now!

**Comment by tkellen** [comment] 2015-07-28 12:11
Resolved in https://github.com/tkellen/js-v8flags/commit/cecc670923fc1930bea9183478d394e7fe2d8892

**Comment by tkellen** [comment] 2015-07-28 12:11
Your example works now. You'll need to re-install tho.

**Closed by tkellen** 2015-07-28 12:11 UTC

**Comment by s-a** [comment] 2015-07-28 12:17
:+1: thanks! it works :)
